// Code generated by go-swagger; DO NOT EDIT.

package assignations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	Assignation "github.com/kathra-project/kathra-core-model-go/models"
)

// AddAssignationReader is a Reader for the AddAssignation structure.
type AddAssignationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddAssignationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddAssignationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAddAssignationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddAssignationOK creates a AddAssignationOK with default headers values
func NewAddAssignationOK() *AddAssignationOK {
	return &AddAssignationOK{}
}

/*AddAssignationOK handles this case with default header values.

Returns the created object
*/
type AddAssignationOK struct {
	Payload Assignation.CatalogEnAssignationtry
}

func (o *AddAssignationOK) Error() string {
	return fmt.Sprintf("[POST /assignations][%d] addAssignationOK  %+v", 200, o.Payload)
}

func (o *AddAssignationOK) GetPayload() Assignation.CatalogEnAssignationtry {
	return o.Payload
}

func (o *AddAssignationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddAssignationUnauthorized creates a AddAssignationUnauthorized with default headers values
func NewAddAssignationUnauthorized() *AddAssignationUnauthorized {
	return &AddAssignationUnauthorized{}
}

/*AddAssignationUnauthorized handles this case with default header values.

Unauthorized
*/
type AddAssignationUnauthorized struct {
}

func (o *AddAssignationUnauthorized) Error() string {
	return fmt.Sprintf("[POST /assignations][%d] addAssignationUnauthorized ", 401)
}

func (o *AddAssignationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
