// Code generated by go-swagger; DO NOT EDIT.

package assignations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAssignationParams creates a new DeleteAssignationParams object
// with the default values initialized.
func NewDeleteAssignationParams() *DeleteAssignationParams {
	var ()
	return &DeleteAssignationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAssignationParamsWithTimeout creates a new DeleteAssignationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAssignationParamsWithTimeout(timeout time.Duration) *DeleteAssignationParams {
	var ()
	return &DeleteAssignationParams{

		timeout: timeout,
	}
}

// NewDeleteAssignationParamsWithContext creates a new DeleteAssignationParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAssignationParamsWithContext(ctx context.Context) *DeleteAssignationParams {
	var ()
	return &DeleteAssignationParams{

		Context: ctx,
	}
}

// NewDeleteAssignationParamsWithHTTPClient creates a new DeleteAssignationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAssignationParamsWithHTTPClient(client *http.Client) *DeleteAssignationParams {
	var ()
	return &DeleteAssignationParams{
		HTTPClient: client,
	}
}

/*DeleteAssignationParams contains all the parameters to send to the API endpoint
for the delete assignation operation typically these are written to a http.Request
*/
type DeleteAssignationParams struct {

	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete assignation params
func (o *DeleteAssignationParams) WithTimeout(timeout time.Duration) *DeleteAssignationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete assignation params
func (o *DeleteAssignationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete assignation params
func (o *DeleteAssignationParams) WithContext(ctx context.Context) *DeleteAssignationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete assignation params
func (o *DeleteAssignationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete assignation params
func (o *DeleteAssignationParams) WithHTTPClient(client *http.Client) *DeleteAssignationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete assignation params
func (o *DeleteAssignationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceID adds the resourceID to the delete assignation params
func (o *DeleteAssignationParams) WithResourceID(resourceID string) *DeleteAssignationParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the delete assignation params
func (o *DeleteAssignationParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAssignationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
