// Code generated by go-swagger; DO NOT EDIT.

package assignations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// GetAssignationsReader is a Reader for the GetAssignations structure.
type GetAssignationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAssignationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAssignationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAssignationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAssignationsOK creates a GetAssignationsOK with default headers values
func NewGetAssignationsOK() *GetAssignationsOK {
	return &GetAssignationsOK{}
}

/*GetAssignationsOK handles this case with default header values.

List of accessible assignations for the authenticated user
*/
type GetAssignationsOK struct {
	Payload []models.Assignation
}

func (o *GetAssignationsOK) Error() string {
	return fmt.Sprintf("[GET /assignations][%d] getAssignationsOK  %+v", 200, o.Payload)
}

func (o *GetAssignationsOK) GetPayload() []models.Assignation {
	return o.Payload
}

func (o *GetAssignationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssignationsUnauthorized creates a GetAssignationsUnauthorized with default headers values
func NewGetAssignationsUnauthorized() *GetAssignationsUnauthorized {
	return &GetAssignationsUnauthorized{}
}

/*GetAssignationsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAssignationsUnauthorized struct {
}

func (o *GetAssignationsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /assignations][%d] getAssignationsUnauthorized ", 401)
}

func (o *GetAssignationsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
