// Code generated by go-swagger; DO NOT EDIT.

package binary_repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteBinaryRepositoryReader is a Reader for the DeleteBinaryRepository structure.
type DeleteBinaryRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBinaryRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteBinaryRepositoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteBinaryRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteBinaryRepositoryOK creates a DeleteBinaryRepositoryOK with default headers values
func NewDeleteBinaryRepositoryOK() *DeleteBinaryRepositoryOK {
	return &DeleteBinaryRepositoryOK{}
}

/*DeleteBinaryRepositoryOK handles this case with default header values.

Object is deleted
*/
type DeleteBinaryRepositoryOK struct {
	Payload string
}

func (o *DeleteBinaryRepositoryOK) Error() string {
	return fmt.Sprintf("[DELETE /binaryrepositories/{resourceId}][%d] deleteBinaryRepositoryOK  %+v", 200, o.Payload)
}

func (o *DeleteBinaryRepositoryOK) GetPayload() string {
	return o.Payload
}

func (o *DeleteBinaryRepositoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBinaryRepositoryUnauthorized creates a DeleteBinaryRepositoryUnauthorized with default headers values
func NewDeleteBinaryRepositoryUnauthorized() *DeleteBinaryRepositoryUnauthorized {
	return &DeleteBinaryRepositoryUnauthorized{}
}

/*DeleteBinaryRepositoryUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteBinaryRepositoryUnauthorized struct {
}

func (o *DeleteBinaryRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /binaryrepositories/{resourceId}][%d] deleteBinaryRepositoryUnauthorized ", 401)
}

func (o *DeleteBinaryRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
