// Code generated by go-swagger; DO NOT EDIT.

package binary_repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteBinaryRepositoryParams creates a new DeleteBinaryRepositoryParams object
// with the default values initialized.
func NewDeleteBinaryRepositoryParams() *DeleteBinaryRepositoryParams {
	var ()
	return &DeleteBinaryRepositoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBinaryRepositoryParamsWithTimeout creates a new DeleteBinaryRepositoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteBinaryRepositoryParamsWithTimeout(timeout time.Duration) *DeleteBinaryRepositoryParams {
	var ()
	return &DeleteBinaryRepositoryParams{

		timeout: timeout,
	}
}

// NewDeleteBinaryRepositoryParamsWithContext creates a new DeleteBinaryRepositoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteBinaryRepositoryParamsWithContext(ctx context.Context) *DeleteBinaryRepositoryParams {
	var ()
	return &DeleteBinaryRepositoryParams{

		Context: ctx,
	}
}

// NewDeleteBinaryRepositoryParamsWithHTTPClient creates a new DeleteBinaryRepositoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteBinaryRepositoryParamsWithHTTPClient(client *http.Client) *DeleteBinaryRepositoryParams {
	var ()
	return &DeleteBinaryRepositoryParams{
		HTTPClient: client,
	}
}

/*DeleteBinaryRepositoryParams contains all the parameters to send to the API endpoint
for the delete binary repository operation typically these are written to a http.Request
*/
type DeleteBinaryRepositoryParams struct {

	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete binary repository params
func (o *DeleteBinaryRepositoryParams) WithTimeout(timeout time.Duration) *DeleteBinaryRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete binary repository params
func (o *DeleteBinaryRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete binary repository params
func (o *DeleteBinaryRepositoryParams) WithContext(ctx context.Context) *DeleteBinaryRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete binary repository params
func (o *DeleteBinaryRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete binary repository params
func (o *DeleteBinaryRepositoryParams) WithHTTPClient(client *http.Client) *DeleteBinaryRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete binary repository params
func (o *DeleteBinaryRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceID adds the resourceID to the delete binary repository params
func (o *DeleteBinaryRepositoryParams) WithResourceID(resourceID string) *DeleteBinaryRepositoryParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the delete binary repository params
func (o *DeleteBinaryRepositoryParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBinaryRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
