// Code generated by go-swagger; DO NOT EDIT.

package binary_repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBinaryRepositoriesParams creates a new GetBinaryRepositoriesParams object
// with the default values initialized.
func NewGetBinaryRepositoriesParams() *GetBinaryRepositoriesParams {

	return &GetBinaryRepositoriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBinaryRepositoriesParamsWithTimeout creates a new GetBinaryRepositoriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBinaryRepositoriesParamsWithTimeout(timeout time.Duration) *GetBinaryRepositoriesParams {

	return &GetBinaryRepositoriesParams{

		timeout: timeout,
	}
}

// NewGetBinaryRepositoriesParamsWithContext creates a new GetBinaryRepositoriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBinaryRepositoriesParamsWithContext(ctx context.Context) *GetBinaryRepositoriesParams {

	return &GetBinaryRepositoriesParams{

		Context: ctx,
	}
}

// NewGetBinaryRepositoriesParamsWithHTTPClient creates a new GetBinaryRepositoriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBinaryRepositoriesParamsWithHTTPClient(client *http.Client) *GetBinaryRepositoriesParams {

	return &GetBinaryRepositoriesParams{
		HTTPClient: client,
	}
}

/*GetBinaryRepositoriesParams contains all the parameters to send to the API endpoint
for the get binary repositories operation typically these are written to a http.Request
*/
type GetBinaryRepositoriesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get binary repositories params
func (o *GetBinaryRepositoriesParams) WithTimeout(timeout time.Duration) *GetBinaryRepositoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get binary repositories params
func (o *GetBinaryRepositoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get binary repositories params
func (o *GetBinaryRepositoriesParams) WithContext(ctx context.Context) *GetBinaryRepositoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get binary repositories params
func (o *GetBinaryRepositoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get binary repositories params
func (o *GetBinaryRepositoriesParams) WithHTTPClient(client *http.Client) *GetBinaryRepositoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get binary repositories params
func (o *GetBinaryRepositoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetBinaryRepositoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
