// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// NewAddGroupParams creates a new AddGroupParams object
// with the default values initialized.
func NewAddGroupParams() *AddGroupParams {
	var ()
	return &AddGroupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddGroupParamsWithTimeout creates a new AddGroupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddGroupParamsWithTimeout(timeout time.Duration) *AddGroupParams {
	var ()
	return &AddGroupParams{

		timeout: timeout,
	}
}

// NewAddGroupParamsWithContext creates a new AddGroupParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddGroupParamsWithContext(ctx context.Context) *AddGroupParams {
	var ()
	return &AddGroupParams{

		Context: ctx,
	}
}

// NewAddGroupParamsWithHTTPClient creates a new AddGroupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddGroupParamsWithHTTPClient(client *http.Client) *AddGroupParams {
	var ()
	return &AddGroupParams{
		HTTPClient: client,
	}
}

/*AddGroupParams contains all the parameters to send to the API endpoint
for the add group operation typically these are written to a http.Request
*/
type AddGroupParams struct {

	/*Group
	  Group object to be created

	*/
	Group *models.Group

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add group params
func (o *AddGroupParams) WithTimeout(timeout time.Duration) *AddGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add group params
func (o *AddGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add group params
func (o *AddGroupParams) WithContext(ctx context.Context) *AddGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add group params
func (o *AddGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add group params
func (o *AddGroupParams) WithHTTPClient(client *http.Client) *AddGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add group params
func (o *AddGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroup adds the group to the add group params
func (o *AddGroupParams) WithGroup(group *models.Group) *AddGroupParams {
	o.SetGroup(group)
	return o
}

// SetGroup adds the group to the add group params
func (o *AddGroupParams) SetGroup(group *models.Group) {
	o.Group = group
}

// WriteToRequest writes these params to a swagger request
func (o *AddGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Group != nil {
		if err := r.SetBodyParam(o.Group); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
