// Code generated by go-swagger; DO NOT EDIT.

package catalog_entry_packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// GetCatalogEntryPackagesReader is a Reader for the GetCatalogEntryPackages structure.
type GetCatalogEntryPackagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCatalogEntryPackagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCatalogEntryPackagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCatalogEntryPackagesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCatalogEntryPackagesOK creates a GetCatalogEntryPackagesOK with default headers values
func NewGetCatalogEntryPackagesOK() *GetCatalogEntryPackagesOK {
	return &GetCatalogEntryPackagesOK{}
}

/*GetCatalogEntryPackagesOK handles this case with default header values.

List of accessible catalogentrypackages for the authenticated user
*/
type GetCatalogEntryPackagesOK struct {
	Payload []*models.CatalogEntryPackage
}

func (o *GetCatalogEntryPackagesOK) Error() string {
	return fmt.Sprintf("[GET /catalogentrypackages][%d] getCatalogEntryPackagesOK  %+v", 200, o.Payload)
}

func (o *GetCatalogEntryPackagesOK) GetPayload() []*models.CatalogEntryPackage {
	return o.Payload
}

func (o *GetCatalogEntryPackagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCatalogEntryPackagesUnauthorized creates a GetCatalogEntryPackagesUnauthorized with default headers values
func NewGetCatalogEntryPackagesUnauthorized() *GetCatalogEntryPackagesUnauthorized {
	return &GetCatalogEntryPackagesUnauthorized{}
}

/*GetCatalogEntryPackagesUnauthorized handles this case with default header values.

Unauthorized
*/
type GetCatalogEntryPackagesUnauthorized struct {
}

func (o *GetCatalogEntryPackagesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /catalogentrypackages][%d] getCatalogEntryPackagesUnauthorized ", 401)
}

func (o *GetCatalogEntryPackagesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
