// Code generated by go-swagger; DO NOT EDIT.

package catalog_entry_packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// NewUpdateCatalogEntryPackageAttributesParams creates a new UpdateCatalogEntryPackageAttributesParams object
// with the default values initialized.
func NewUpdateCatalogEntryPackageAttributesParams() *UpdateCatalogEntryPackageAttributesParams {
	var ()
	return &UpdateCatalogEntryPackageAttributesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCatalogEntryPackageAttributesParamsWithTimeout creates a new UpdateCatalogEntryPackageAttributesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateCatalogEntryPackageAttributesParamsWithTimeout(timeout time.Duration) *UpdateCatalogEntryPackageAttributesParams {
	var ()
	return &UpdateCatalogEntryPackageAttributesParams{

		timeout: timeout,
	}
}

// NewUpdateCatalogEntryPackageAttributesParamsWithContext creates a new UpdateCatalogEntryPackageAttributesParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateCatalogEntryPackageAttributesParamsWithContext(ctx context.Context) *UpdateCatalogEntryPackageAttributesParams {
	var ()
	return &UpdateCatalogEntryPackageAttributesParams{

		Context: ctx,
	}
}

// NewUpdateCatalogEntryPackageAttributesParamsWithHTTPClient creates a new UpdateCatalogEntryPackageAttributesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateCatalogEntryPackageAttributesParamsWithHTTPClient(client *http.Client) *UpdateCatalogEntryPackageAttributesParams {
	var ()
	return &UpdateCatalogEntryPackageAttributesParams{
		HTTPClient: client,
	}
}

/*UpdateCatalogEntryPackageAttributesParams contains all the parameters to send to the API endpoint
for the update catalog entry package attributes operation typically these are written to a http.Request
*/
type UpdateCatalogEntryPackageAttributesParams struct {

	/*Catalogentrypackage
	  CatalogEntryPackage object to be updated

	*/
	Catalogentrypackage *models.CatalogEntryPackage
	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update catalog entry package attributes params
func (o *UpdateCatalogEntryPackageAttributesParams) WithTimeout(timeout time.Duration) *UpdateCatalogEntryPackageAttributesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update catalog entry package attributes params
func (o *UpdateCatalogEntryPackageAttributesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update catalog entry package attributes params
func (o *UpdateCatalogEntryPackageAttributesParams) WithContext(ctx context.Context) *UpdateCatalogEntryPackageAttributesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update catalog entry package attributes params
func (o *UpdateCatalogEntryPackageAttributesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update catalog entry package attributes params
func (o *UpdateCatalogEntryPackageAttributesParams) WithHTTPClient(client *http.Client) *UpdateCatalogEntryPackageAttributesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update catalog entry package attributes params
func (o *UpdateCatalogEntryPackageAttributesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCatalogentrypackage adds the catalogentrypackage to the update catalog entry package attributes params
func (o *UpdateCatalogEntryPackageAttributesParams) WithCatalogentrypackage(catalogentrypackage *models.CatalogEntryPackage) *UpdateCatalogEntryPackageAttributesParams {
	o.SetCatalogentrypackage(catalogentrypackage)
	return o
}

// SetCatalogentrypackage adds the catalogentrypackage to the update catalog entry package attributes params
func (o *UpdateCatalogEntryPackageAttributesParams) SetCatalogentrypackage(catalogentrypackage *models.CatalogEntryPackage) {
	o.Catalogentrypackage = catalogentrypackage
}

// WithResourceID adds the resourceID to the update catalog entry package attributes params
func (o *UpdateCatalogEntryPackageAttributesParams) WithResourceID(resourceID string) *UpdateCatalogEntryPackageAttributesParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the update catalog entry package attributes params
func (o *UpdateCatalogEntryPackageAttributesParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCatalogEntryPackageAttributesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Catalogentrypackage != nil {
		if err := r.SetBodyParam(o.Catalogentrypackage); err != nil {
			return err
		}
	}

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
