// Code generated by go-swagger; DO NOT EDIT.

package key_pairs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteKeyPairReader is a Reader for the DeleteKeyPair structure.
type DeleteKeyPairReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteKeyPairReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteKeyPairOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteKeyPairUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteKeyPairOK creates a DeleteKeyPairOK with default headers values
func NewDeleteKeyPairOK() *DeleteKeyPairOK {
	return &DeleteKeyPairOK{}
}

/*DeleteKeyPairOK handles this case with default header values.

Object is deleted
*/
type DeleteKeyPairOK struct {
	Payload string
}

func (o *DeleteKeyPairOK) Error() string {
	return fmt.Sprintf("[DELETE /keypairs/{resourceId}][%d] deleteKeyPairOK  %+v", 200, o.Payload)
}

func (o *DeleteKeyPairOK) GetPayload() string {
	return o.Payload
}

func (o *DeleteKeyPairOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteKeyPairUnauthorized creates a DeleteKeyPairUnauthorized with default headers values
func NewDeleteKeyPairUnauthorized() *DeleteKeyPairUnauthorized {
	return &DeleteKeyPairUnauthorized{}
}

/*DeleteKeyPairUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteKeyPairUnauthorized struct {
}

func (o *DeleteKeyPairUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /keypairs/{resourceId}][%d] deleteKeyPairUnauthorized ", 401)
}

func (o *DeleteKeyPairUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
