// Code generated by go-swagger; DO NOT EDIT.

package key_pairs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteKeyPairParams creates a new DeleteKeyPairParams object
// with the default values initialized.
func NewDeleteKeyPairParams() *DeleteKeyPairParams {
	var ()
	return &DeleteKeyPairParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteKeyPairParamsWithTimeout creates a new DeleteKeyPairParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteKeyPairParamsWithTimeout(timeout time.Duration) *DeleteKeyPairParams {
	var ()
	return &DeleteKeyPairParams{

		timeout: timeout,
	}
}

// NewDeleteKeyPairParamsWithContext creates a new DeleteKeyPairParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteKeyPairParamsWithContext(ctx context.Context) *DeleteKeyPairParams {
	var ()
	return &DeleteKeyPairParams{

		Context: ctx,
	}
}

// NewDeleteKeyPairParamsWithHTTPClient creates a new DeleteKeyPairParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteKeyPairParamsWithHTTPClient(client *http.Client) *DeleteKeyPairParams {
	var ()
	return &DeleteKeyPairParams{
		HTTPClient: client,
	}
}

/*DeleteKeyPairParams contains all the parameters to send to the API endpoint
for the delete key pair operation typically these are written to a http.Request
*/
type DeleteKeyPairParams struct {

	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete key pair params
func (o *DeleteKeyPairParams) WithTimeout(timeout time.Duration) *DeleteKeyPairParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete key pair params
func (o *DeleteKeyPairParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete key pair params
func (o *DeleteKeyPairParams) WithContext(ctx context.Context) *DeleteKeyPairParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete key pair params
func (o *DeleteKeyPairParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete key pair params
func (o *DeleteKeyPairParams) WithHTTPClient(client *http.Client) *DeleteKeyPairParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete key pair params
func (o *DeleteKeyPairParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceID adds the resourceID to the delete key pair params
func (o *DeleteKeyPairParams) WithResourceID(resourceID string) *DeleteKeyPairParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the delete key pair params
func (o *DeleteKeyPairParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteKeyPairParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
