// Code generated by go-swagger; DO NOT EDIT.

package key_pairs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetKeyPairParams creates a new GetKeyPairParams object
// with the default values initialized.
func NewGetKeyPairParams() *GetKeyPairParams {
	var ()
	return &GetKeyPairParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetKeyPairParamsWithTimeout creates a new GetKeyPairParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetKeyPairParamsWithTimeout(timeout time.Duration) *GetKeyPairParams {
	var ()
	return &GetKeyPairParams{

		timeout: timeout,
	}
}

// NewGetKeyPairParamsWithContext creates a new GetKeyPairParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetKeyPairParamsWithContext(ctx context.Context) *GetKeyPairParams {
	var ()
	return &GetKeyPairParams{

		Context: ctx,
	}
}

// NewGetKeyPairParamsWithHTTPClient creates a new GetKeyPairParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetKeyPairParamsWithHTTPClient(client *http.Client) *GetKeyPairParams {
	var ()
	return &GetKeyPairParams{
		HTTPClient: client,
	}
}

/*GetKeyPairParams contains all the parameters to send to the API endpoint
for the get key pair operation typically these are written to a http.Request
*/
type GetKeyPairParams struct {

	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get key pair params
func (o *GetKeyPairParams) WithTimeout(timeout time.Duration) *GetKeyPairParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get key pair params
func (o *GetKeyPairParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get key pair params
func (o *GetKeyPairParams) WithContext(ctx context.Context) *GetKeyPairParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get key pair params
func (o *GetKeyPairParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get key pair params
func (o *GetKeyPairParams) WithHTTPClient(client *http.Client) *GetKeyPairParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get key pair params
func (o *GetKeyPairParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceID adds the resourceID to the get key pair params
func (o *GetKeyPairParams) WithResourceID(resourceID string) *GetKeyPairParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the get key pair params
func (o *GetKeyPairParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetKeyPairParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
