// Code generated by go-swagger; DO NOT EDIT.

package catalog_entries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCatalogEntriesParams creates a new GetCatalogEntriesParams object
// with the default values initialized.
func NewGetCatalogEntriesParams() *GetCatalogEntriesParams {

	return &GetCatalogEntriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCatalogEntriesParamsWithTimeout creates a new GetCatalogEntriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCatalogEntriesParamsWithTimeout(timeout time.Duration) *GetCatalogEntriesParams {

	return &GetCatalogEntriesParams{

		timeout: timeout,
	}
}

// NewGetCatalogEntriesParamsWithContext creates a new GetCatalogEntriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCatalogEntriesParamsWithContext(ctx context.Context) *GetCatalogEntriesParams {

	return &GetCatalogEntriesParams{

		Context: ctx,
	}
}

// NewGetCatalogEntriesParamsWithHTTPClient creates a new GetCatalogEntriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCatalogEntriesParamsWithHTTPClient(client *http.Client) *GetCatalogEntriesParams {

	return &GetCatalogEntriesParams{
		HTTPClient: client,
	}
}

/*GetCatalogEntriesParams contains all the parameters to send to the API endpoint
for the get catalog entries operation typically these are written to a http.Request
*/
type GetCatalogEntriesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get catalog entries params
func (o *GetCatalogEntriesParams) WithTimeout(timeout time.Duration) *GetCatalogEntriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get catalog entries params
func (o *GetCatalogEntriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get catalog entries params
func (o *GetCatalogEntriesParams) WithContext(ctx context.Context) *GetCatalogEntriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get catalog entries params
func (o *GetCatalogEntriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get catalog entries params
func (o *GetCatalogEntriesParams) WithHTTPClient(client *http.Client) *GetCatalogEntriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get catalog entries params
func (o *GetCatalogEntriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCatalogEntriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
