// Code generated by go-swagger; DO NOT EDIT.

package catalog_entries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// GetCatalogEntryReader is a Reader for the GetCatalogEntry structure.
type GetCatalogEntryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCatalogEntryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCatalogEntryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCatalogEntryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCatalogEntryOK creates a GetCatalogEntryOK with default headers values
func NewGetCatalogEntryOK() *GetCatalogEntryOK {
	return &GetCatalogEntryOK{}
}

/*GetCatalogEntryOK handles this case with default header values.

Returns the object
*/
type GetCatalogEntryOK struct {
	Payload models.CatalogEntry
}

func (o *GetCatalogEntryOK) Error() string {
	return fmt.Sprintf("[GET /catalogentries/{resourceId}][%d] getCatalogEntryOK  %+v", 200, o.Payload)
}

func (o *GetCatalogEntryOK) GetPayload() models.CatalogEntry {
	return o.Payload
}

func (o *GetCatalogEntryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCatalogEntryUnauthorized creates a GetCatalogEntryUnauthorized with default headers values
func NewGetCatalogEntryUnauthorized() *GetCatalogEntryUnauthorized {
	return &GetCatalogEntryUnauthorized{}
}

/*GetCatalogEntryUnauthorized handles this case with default header values.

Unauthorized
*/
type GetCatalogEntryUnauthorized struct {
}

func (o *GetCatalogEntryUnauthorized) Error() string {
	return fmt.Sprintf("[GET /catalogentries/{resourceId}][%d] getCatalogEntryUnauthorized ", 401)
}

func (o *GetCatalogEntryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
