// Code generated by go-swagger; DO NOT EDIT.

package catalog_entries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	CatalogEntry "github.com/kathra-project/kathra-core-model-go/models"
)

// NewUpdateCatalogEntryParams creates a new UpdateCatalogEntryParams object
// with the default values initialized.
func NewUpdateCatalogEntryParams() *UpdateCatalogEntryParams {
	var ()
	return &UpdateCatalogEntryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCatalogEntryParamsWithTimeout creates a new UpdateCatalogEntryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateCatalogEntryParamsWithTimeout(timeout time.Duration) *UpdateCatalogEntryParams {
	var ()
	return &UpdateCatalogEntryParams{

		timeout: timeout,
	}
}

// NewUpdateCatalogEntryParamsWithContext creates a new UpdateCatalogEntryParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateCatalogEntryParamsWithContext(ctx context.Context) *UpdateCatalogEntryParams {
	var ()
	return &UpdateCatalogEntryParams{

		Context: ctx,
	}
}

// NewUpdateCatalogEntryParamsWithHTTPClient creates a new UpdateCatalogEntryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateCatalogEntryParamsWithHTTPClient(client *http.Client) *UpdateCatalogEntryParams {
	var ()
	return &UpdateCatalogEntryParams{
		HTTPClient: client,
	}
}

/*UpdateCatalogEntryParams contains all the parameters to send to the API endpoint
for the update catalog entry operation typically these are written to a http.Request
*/
type UpdateCatalogEntryParams struct {

	/*Catalogentry
	  CatalogEntry object to be updated

	*/
	Catalogentry CatalogEntry.CatalogEntry
	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update catalog entry params
func (o *UpdateCatalogEntryParams) WithTimeout(timeout time.Duration) *UpdateCatalogEntryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update catalog entry params
func (o *UpdateCatalogEntryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update catalog entry params
func (o *UpdateCatalogEntryParams) WithContext(ctx context.Context) *UpdateCatalogEntryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update catalog entry params
func (o *UpdateCatalogEntryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update catalog entry params
func (o *UpdateCatalogEntryParams) WithHTTPClient(client *http.Client) *UpdateCatalogEntryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update catalog entry params
func (o *UpdateCatalogEntryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCatalogentry adds the catalogentry to the update catalog entry params
func (o *UpdateCatalogEntryParams) WithCatalogentry(catalogentry CatalogEntry.CatalogEntry) *UpdateCatalogEntryParams {
	o.SetCatalogentry(catalogentry)
	return o
}

// SetCatalogentry adds the catalogentry to the update catalog entry params
func (o *UpdateCatalogEntryParams) SetCatalogentry(catalogentry CatalogEntry.CatalogEntry) {
	o.Catalogentry = catalogentry
}

// WithResourceID adds the resourceID to the update catalog entry params
func (o *UpdateCatalogEntryParams) WithResourceID(resourceID string) *UpdateCatalogEntryParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the update catalog entry params
func (o *UpdateCatalogEntryParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCatalogEntryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Catalogentry != nil {
		if err := r.SetBodyParam(o.Catalogentry); err != nil {
			return err
		}
	}

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
