// Code generated by go-swagger; DO NOT EDIT.

package source_repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSourceRepositoryParams creates a new DeleteSourceRepositoryParams object
// with the default values initialized.
func NewDeleteSourceRepositoryParams() *DeleteSourceRepositoryParams {
	var ()
	return &DeleteSourceRepositoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSourceRepositoryParamsWithTimeout creates a new DeleteSourceRepositoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSourceRepositoryParamsWithTimeout(timeout time.Duration) *DeleteSourceRepositoryParams {
	var ()
	return &DeleteSourceRepositoryParams{

		timeout: timeout,
	}
}

// NewDeleteSourceRepositoryParamsWithContext creates a new DeleteSourceRepositoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSourceRepositoryParamsWithContext(ctx context.Context) *DeleteSourceRepositoryParams {
	var ()
	return &DeleteSourceRepositoryParams{

		Context: ctx,
	}
}

// NewDeleteSourceRepositoryParamsWithHTTPClient creates a new DeleteSourceRepositoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSourceRepositoryParamsWithHTTPClient(client *http.Client) *DeleteSourceRepositoryParams {
	var ()
	return &DeleteSourceRepositoryParams{
		HTTPClient: client,
	}
}

/*DeleteSourceRepositoryParams contains all the parameters to send to the API endpoint
for the delete source repository operation typically these are written to a http.Request
*/
type DeleteSourceRepositoryParams struct {

	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete source repository params
func (o *DeleteSourceRepositoryParams) WithTimeout(timeout time.Duration) *DeleteSourceRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete source repository params
func (o *DeleteSourceRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete source repository params
func (o *DeleteSourceRepositoryParams) WithContext(ctx context.Context) *DeleteSourceRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete source repository params
func (o *DeleteSourceRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete source repository params
func (o *DeleteSourceRepositoryParams) WithHTTPClient(client *http.Client) *DeleteSourceRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete source repository params
func (o *DeleteSourceRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceID adds the resourceID to the delete source repository params
func (o *DeleteSourceRepositoryParams) WithResourceID(resourceID string) *DeleteSourceRepositoryParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the delete source repository params
func (o *DeleteSourceRepositoryParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSourceRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
