// Code generated by go-swagger; DO NOT EDIT.

package source_repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	SourceRepository "github.com/kathra-project/kathra-core-model-go/models"
)

// GetSourceRepositoriesReader is a Reader for the GetSourceRepositories structure.
type GetSourceRepositoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSourceRepositoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSourceRepositoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetSourceRepositoriesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSourceRepositoriesOK creates a GetSourceRepositoriesOK with default headers values
func NewGetSourceRepositoriesOK() *GetSourceRepositoriesOK {
	return &GetSourceRepositoriesOK{}
}

/*GetSourceRepositoriesOK handles this case with default header values.

List of accessible sourcerepositories for the authenticated user
*/
type GetSourceRepositoriesOK struct {
	Payload []SourceRepository.SourceRepository
}

func (o *GetSourceRepositoriesOK) Error() string {
	return fmt.Sprintf("[GET /sourcerepositories][%d] getSourceRepositoriesOK  %+v", 200, o.Payload)
}

func (o *GetSourceRepositoriesOK) GetPayload() []SourceRepository.SourceRepository {
	return o.Payload
}

func (o *GetSourceRepositoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSourceRepositoriesUnauthorized creates a GetSourceRepositoriesUnauthorized with default headers values
func NewGetSourceRepositoriesUnauthorized() *GetSourceRepositoriesUnauthorized {
	return &GetSourceRepositoriesUnauthorized{}
}

/*GetSourceRepositoriesUnauthorized handles this case with default header values.

Unauthorized
*/
type GetSourceRepositoriesUnauthorized struct {
}

func (o *GetSourceRepositoriesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /sourcerepositories][%d] getSourceRepositoriesUnauthorized ", 401)
}

func (o *GetSourceRepositoriesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
