// Code generated by go-swagger; DO NOT EDIT.

package source_repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSourceRepositoriesParams creates a new GetSourceRepositoriesParams object
// with the default values initialized.
func NewGetSourceRepositoriesParams() *GetSourceRepositoriesParams {

	return &GetSourceRepositoriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSourceRepositoriesParamsWithTimeout creates a new GetSourceRepositoriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSourceRepositoriesParamsWithTimeout(timeout time.Duration) *GetSourceRepositoriesParams {

	return &GetSourceRepositoriesParams{

		timeout: timeout,
	}
}

// NewGetSourceRepositoriesParamsWithContext creates a new GetSourceRepositoriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSourceRepositoriesParamsWithContext(ctx context.Context) *GetSourceRepositoriesParams {

	return &GetSourceRepositoriesParams{

		Context: ctx,
	}
}

// NewGetSourceRepositoriesParamsWithHTTPClient creates a new GetSourceRepositoriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSourceRepositoriesParamsWithHTTPClient(client *http.Client) *GetSourceRepositoriesParams {

	return &GetSourceRepositoriesParams{
		HTTPClient: client,
	}
}

/*GetSourceRepositoriesParams contains all the parameters to send to the API endpoint
for the get source repositories operation typically these are written to a http.Request
*/
type GetSourceRepositoriesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get source repositories params
func (o *GetSourceRepositoriesParams) WithTimeout(timeout time.Duration) *GetSourceRepositoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get source repositories params
func (o *GetSourceRepositoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get source repositories params
func (o *GetSourceRepositoriesParams) WithContext(ctx context.Context) *GetSourceRepositoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get source repositories params
func (o *GetSourceRepositoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get source repositories params
func (o *GetSourceRepositoriesParams) WithHTTPClient(client *http.Client) *GetSourceRepositoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get source repositories params
func (o *GetSourceRepositoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSourceRepositoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
