// Code generated by go-swagger; DO NOT EDIT.

package implementation_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	ImplementationVersion "github.com/kathra-project/kathra-core-model-go/models"
)

// GetImplementationVersionsReader is a Reader for the GetImplementationVersions structure.
type GetImplementationVersionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImplementationVersionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetImplementationVersionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetImplementationVersionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetImplementationVersionsOK creates a GetImplementationVersionsOK with default headers values
func NewGetImplementationVersionsOK() *GetImplementationVersionsOK {
	return &GetImplementationVersionsOK{}
}

/*GetImplementationVersionsOK handles this case with default header values.

List of accessible implementationversions for the authenticated user
*/
type GetImplementationVersionsOK struct {
	Payload []ImplementationVersion.ImplementationVersion
}

func (o *GetImplementationVersionsOK) Error() string {
	return fmt.Sprintf("[GET /implementationversions][%d] getImplementationVersionsOK  %+v", 200, o.Payload)
}

func (o *GetImplementationVersionsOK) GetPayload() []ImplementationVersion.ImplementationVersion {
	return o.Payload
}

func (o *GetImplementationVersionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImplementationVersionsUnauthorized creates a GetImplementationVersionsUnauthorized with default headers values
func NewGetImplementationVersionsUnauthorized() *GetImplementationVersionsUnauthorized {
	return &GetImplementationVersionsUnauthorized{}
}

/*GetImplementationVersionsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetImplementationVersionsUnauthorized struct {
}

func (o *GetImplementationVersionsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /implementationversions][%d] getImplementationVersionsUnauthorized ", 401)
}

func (o *GetImplementationVersionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
