// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// NewUpdateUserAttributesParams creates a new UpdateUserAttributesParams object
// with the default values initialized.
func NewUpdateUserAttributesParams() *UpdateUserAttributesParams {
	var ()
	return &UpdateUserAttributesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateUserAttributesParamsWithTimeout creates a new UpdateUserAttributesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateUserAttributesParamsWithTimeout(timeout time.Duration) *UpdateUserAttributesParams {
	var ()
	return &UpdateUserAttributesParams{

		timeout: timeout,
	}
}

// NewUpdateUserAttributesParamsWithContext creates a new UpdateUserAttributesParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateUserAttributesParamsWithContext(ctx context.Context) *UpdateUserAttributesParams {
	var ()
	return &UpdateUserAttributesParams{

		Context: ctx,
	}
}

// NewUpdateUserAttributesParamsWithHTTPClient creates a new UpdateUserAttributesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateUserAttributesParamsWithHTTPClient(client *http.Client) *UpdateUserAttributesParams {
	var ()
	return &UpdateUserAttributesParams{
		HTTPClient: client,
	}
}

/*UpdateUserAttributesParams contains all the parameters to send to the API endpoint
for the update user attributes operation typically these are written to a http.Request
*/
type UpdateUserAttributesParams struct {

	/*ResourceID
	  resource's id

	*/
	ResourceID string
	/*User
	  User object to be updated

	*/
	User models.User

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update user attributes params
func (o *UpdateUserAttributesParams) WithTimeout(timeout time.Duration) *UpdateUserAttributesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update user attributes params
func (o *UpdateUserAttributesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update user attributes params
func (o *UpdateUserAttributesParams) WithContext(ctx context.Context) *UpdateUserAttributesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update user attributes params
func (o *UpdateUserAttributesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update user attributes params
func (o *UpdateUserAttributesParams) WithHTTPClient(client *http.Client) *UpdateUserAttributesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update user attributes params
func (o *UpdateUserAttributesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceID adds the resourceID to the update user attributes params
func (o *UpdateUserAttributesParams) WithResourceID(resourceID string) *UpdateUserAttributesParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the update user attributes params
func (o *UpdateUserAttributesParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WithUser adds the user to the update user attributes params
func (o *UpdateUserAttributesParams) WithUser(user models.User) *UpdateUserAttributesParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the update user attributes params
func (o *UpdateUserAttributesParams) SetUser(user models.User) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateUserAttributesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if o.User != nil {
		if err := r.SetBodyParam(o.User); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
