// Code generated by go-swagger; DO NOT EDIT.

package pipelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	Pipeline "github.com/kathra-project/kathra-core-model-go/models"
)

// GetPipelineReader is a Reader for the GetPipeline structure.
type GetPipelineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPipelineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPipelineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetPipelineUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPipelineOK creates a GetPipelineOK with default headers values
func NewGetPipelineOK() *GetPipelineOK {
	return &GetPipelineOK{}
}

/*GetPipelineOK handles this case with default header values.

Returns the object
*/
type GetPipelineOK struct {
	Payload Pipeline.Pipeline
}

func (o *GetPipelineOK) Error() string {
	return fmt.Sprintf("[GET /pipelines/{resourceId}][%d] getPipelineOK  %+v", 200, o.Payload)
}

func (o *GetPipelineOK) GetPayload() Pipeline.Pipeline {
	return o.Payload
}

func (o *GetPipelineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPipelineUnauthorized creates a GetPipelineUnauthorized with default headers values
func NewGetPipelineUnauthorized() *GetPipelineUnauthorized {
	return &GetPipelineUnauthorized{}
}

/*GetPipelineUnauthorized handles this case with default header values.

Unauthorized
*/
type GetPipelineUnauthorized struct {
}

func (o *GetPipelineUnauthorized) Error() string {
	return fmt.Sprintf("[GET /pipelines/{resourceId}][%d] getPipelineUnauthorized ", 401)
}

func (o *GetPipelineUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
