// Code generated by go-swagger; DO NOT EDIT.

package pipelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// NewUpdatePipelineParams creates a new UpdatePipelineParams object
// with the default values initialized.
func NewUpdatePipelineParams() *UpdatePipelineParams {
	var ()
	return &UpdatePipelineParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePipelineParamsWithTimeout creates a new UpdatePipelineParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdatePipelineParamsWithTimeout(timeout time.Duration) *UpdatePipelineParams {
	var ()
	return &UpdatePipelineParams{

		timeout: timeout,
	}
}

// NewUpdatePipelineParamsWithContext creates a new UpdatePipelineParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdatePipelineParamsWithContext(ctx context.Context) *UpdatePipelineParams {
	var ()
	return &UpdatePipelineParams{

		Context: ctx,
	}
}

// NewUpdatePipelineParamsWithHTTPClient creates a new UpdatePipelineParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdatePipelineParamsWithHTTPClient(client *http.Client) *UpdatePipelineParams {
	var ()
	return &UpdatePipelineParams{
		HTTPClient: client,
	}
}

/*UpdatePipelineParams contains all the parameters to send to the API endpoint
for the update pipeline operation typically these are written to a http.Request
*/
type UpdatePipelineParams struct {

	/*Pipeline
	  Pipeline object to be updated

	*/
	Pipeline models.Pipeline
	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update pipeline params
func (o *UpdatePipelineParams) WithTimeout(timeout time.Duration) *UpdatePipelineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update pipeline params
func (o *UpdatePipelineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update pipeline params
func (o *UpdatePipelineParams) WithContext(ctx context.Context) *UpdatePipelineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update pipeline params
func (o *UpdatePipelineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update pipeline params
func (o *UpdatePipelineParams) WithHTTPClient(client *http.Client) *UpdatePipelineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update pipeline params
func (o *UpdatePipelineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPipeline adds the pipeline to the update pipeline params
func (o *UpdatePipelineParams) WithPipeline(pipeline models.Pipeline) *UpdatePipelineParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the update pipeline params
func (o *UpdatePipelineParams) SetPipeline(pipeline models.Pipeline) {
	o.Pipeline = pipeline
}

// WithResourceID adds the resourceID to the update pipeline params
func (o *UpdatePipelineParams) WithResourceID(resourceID string) *UpdatePipelineParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the update pipeline params
func (o *UpdatePipelineParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePipelineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Pipeline != nil {
		if err := r.SetBodyParam(o.Pipeline); err != nil {
			return err
		}
	}

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
