// Code generated by go-swagger; DO NOT EDIT.

package pipelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	Pipeline "github.com/kathra-project/kathra-core-model-go/models"
)

// NewUpdatePipelineAttributesParams creates a new UpdatePipelineAttributesParams object
// with the default values initialized.
func NewUpdatePipelineAttributesParams() *UpdatePipelineAttributesParams {
	var ()
	return &UpdatePipelineAttributesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePipelineAttributesParamsWithTimeout creates a new UpdatePipelineAttributesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdatePipelineAttributesParamsWithTimeout(timeout time.Duration) *UpdatePipelineAttributesParams {
	var ()
	return &UpdatePipelineAttributesParams{

		timeout: timeout,
	}
}

// NewUpdatePipelineAttributesParamsWithContext creates a new UpdatePipelineAttributesParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdatePipelineAttributesParamsWithContext(ctx context.Context) *UpdatePipelineAttributesParams {
	var ()
	return &UpdatePipelineAttributesParams{

		Context: ctx,
	}
}

// NewUpdatePipelineAttributesParamsWithHTTPClient creates a new UpdatePipelineAttributesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdatePipelineAttributesParamsWithHTTPClient(client *http.Client) *UpdatePipelineAttributesParams {
	var ()
	return &UpdatePipelineAttributesParams{
		HTTPClient: client,
	}
}

/*UpdatePipelineAttributesParams contains all the parameters to send to the API endpoint
for the update pipeline attributes operation typically these are written to a http.Request
*/
type UpdatePipelineAttributesParams struct {

	/*Pipeline
	  Pipeline object to be updated

	*/
	Pipeline Pipeline.Pipeline
	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update pipeline attributes params
func (o *UpdatePipelineAttributesParams) WithTimeout(timeout time.Duration) *UpdatePipelineAttributesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update pipeline attributes params
func (o *UpdatePipelineAttributesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update pipeline attributes params
func (o *UpdatePipelineAttributesParams) WithContext(ctx context.Context) *UpdatePipelineAttributesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update pipeline attributes params
func (o *UpdatePipelineAttributesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update pipeline attributes params
func (o *UpdatePipelineAttributesParams) WithHTTPClient(client *http.Client) *UpdatePipelineAttributesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update pipeline attributes params
func (o *UpdatePipelineAttributesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPipeline adds the pipeline to the update pipeline attributes params
func (o *UpdatePipelineAttributesParams) WithPipeline(pipeline Pipeline.Pipeline) *UpdatePipelineAttributesParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the update pipeline attributes params
func (o *UpdatePipelineAttributesParams) SetPipeline(pipeline Pipeline.Pipeline) {
	o.Pipeline = pipeline
}

// WithResourceID adds the resourceID to the update pipeline attributes params
func (o *UpdatePipelineAttributesParams) WithResourceID(resourceID string) *UpdatePipelineAttributesParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the update pipeline attributes params
func (o *UpdatePipelineAttributesParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePipelineAttributesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Pipeline != nil {
		if err := r.SetBodyParam(o.Pipeline); err != nil {
			return err
		}
	}

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
