// Code generated by go-swagger; DO NOT EDIT.

package implementations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// GetImplementationReader is a Reader for the GetImplementation structure.
type GetImplementationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImplementationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetImplementationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetImplementationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetImplementationOK creates a GetImplementationOK with default headers values
func NewGetImplementationOK() *GetImplementationOK {
	return &GetImplementationOK{}
}

/*GetImplementationOK handles this case with default header values.

Returns the object
*/
type GetImplementationOK struct {
	Payload models.Implementation
}

func (o *GetImplementationOK) Error() string {
	return fmt.Sprintf("[GET /implementations/{resourceId}][%d] getImplementationOK  %+v", 200, o.Payload)
}

func (o *GetImplementationOK) GetPayload() models.Implementation {
	return o.Payload
}

func (o *GetImplementationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImplementationUnauthorized creates a GetImplementationUnauthorized with default headers values
func NewGetImplementationUnauthorized() *GetImplementationUnauthorized {
	return &GetImplementationUnauthorized{}
}

/*GetImplementationUnauthorized handles this case with default header values.

Unauthorized
*/
type GetImplementationUnauthorized struct {
}

func (o *GetImplementationUnauthorized) Error() string {
	return fmt.Sprintf("[GET /implementations/{resourceId}][%d] getImplementationUnauthorized ", 401)
}

func (o *GetImplementationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
