// Code generated by go-swagger; DO NOT EDIT.

package implementations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// GetImplementationsReader is a Reader for the GetImplementations structure.
type GetImplementationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImplementationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetImplementationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetImplementationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetImplementationsOK creates a GetImplementationsOK with default headers values
func NewGetImplementationsOK() *GetImplementationsOK {
	return &GetImplementationsOK{}
}

/*GetImplementationsOK handles this case with default header values.

List of accessible implementations for the authenticated user
*/
type GetImplementationsOK struct {
	Payload []*models.Implementation
}

func (o *GetImplementationsOK) Error() string {
	return fmt.Sprintf("[GET /implementations][%d] getImplementationsOK  %+v", 200, o.Payload)
}

func (o *GetImplementationsOK) GetPayload() []*models.Implementation {
	return o.Payload
}

func (o *GetImplementationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImplementationsUnauthorized creates a GetImplementationsUnauthorized with default headers values
func NewGetImplementationsUnauthorized() *GetImplementationsUnauthorized {
	return &GetImplementationsUnauthorized{}
}

/*GetImplementationsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetImplementationsUnauthorized struct {
}

func (o *GetImplementationsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /implementations][%d] getImplementationsUnauthorized ", 401)
}

func (o *GetImplementationsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
