// Code generated by go-swagger; DO NOT EDIT.

package implementations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	Implementation "github.com/kathra-project/kathra-core-model-go/models"
)

// NewUpdateImplementationParams creates a new UpdateImplementationParams object
// with the default values initialized.
func NewUpdateImplementationParams() *UpdateImplementationParams {
	var ()
	return &UpdateImplementationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateImplementationParamsWithTimeout creates a new UpdateImplementationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateImplementationParamsWithTimeout(timeout time.Duration) *UpdateImplementationParams {
	var ()
	return &UpdateImplementationParams{

		timeout: timeout,
	}
}

// NewUpdateImplementationParamsWithContext creates a new UpdateImplementationParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateImplementationParamsWithContext(ctx context.Context) *UpdateImplementationParams {
	var ()
	return &UpdateImplementationParams{

		Context: ctx,
	}
}

// NewUpdateImplementationParamsWithHTTPClient creates a new UpdateImplementationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateImplementationParamsWithHTTPClient(client *http.Client) *UpdateImplementationParams {
	var ()
	return &UpdateImplementationParams{
		HTTPClient: client,
	}
}

/*UpdateImplementationParams contains all the parameters to send to the API endpoint
for the update implementation operation typically these are written to a http.Request
*/
type UpdateImplementationParams struct {

	/*Implementation
	  Implementation object to be updated

	*/
	Implementation Implementation.Implementation
	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update implementation params
func (o *UpdateImplementationParams) WithTimeout(timeout time.Duration) *UpdateImplementationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update implementation params
func (o *UpdateImplementationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update implementation params
func (o *UpdateImplementationParams) WithContext(ctx context.Context) *UpdateImplementationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update implementation params
func (o *UpdateImplementationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update implementation params
func (o *UpdateImplementationParams) WithHTTPClient(client *http.Client) *UpdateImplementationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update implementation params
func (o *UpdateImplementationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImplementation adds the implementation to the update implementation params
func (o *UpdateImplementationParams) WithImplementation(implementation Implementation.Implementation) *UpdateImplementationParams {
	o.SetImplementation(implementation)
	return o
}

// SetImplementation adds the implementation to the update implementation params
func (o *UpdateImplementationParams) SetImplementation(implementation Implementation.Implementation) {
	o.Implementation = implementation
}

// WithResourceID adds the resourceID to the update implementation params
func (o *UpdateImplementationParams) WithResourceID(resourceID string) *UpdateImplementationParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the update implementation params
func (o *UpdateImplementationParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateImplementationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Implementation != nil {
		if err := r.SetBodyParam(o.Implementation); err != nil {
			return err
		}
	}

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
