// Code generated by go-swagger; DO NOT EDIT.

package implementations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// NewUpdateImplementationAttributesParams creates a new UpdateImplementationAttributesParams object
// with the default values initialized.
func NewUpdateImplementationAttributesParams() *UpdateImplementationAttributesParams {
	var ()
	return &UpdateImplementationAttributesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateImplementationAttributesParamsWithTimeout creates a new UpdateImplementationAttributesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateImplementationAttributesParamsWithTimeout(timeout time.Duration) *UpdateImplementationAttributesParams {
	var ()
	return &UpdateImplementationAttributesParams{

		timeout: timeout,
	}
}

// NewUpdateImplementationAttributesParamsWithContext creates a new UpdateImplementationAttributesParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateImplementationAttributesParamsWithContext(ctx context.Context) *UpdateImplementationAttributesParams {
	var ()
	return &UpdateImplementationAttributesParams{

		Context: ctx,
	}
}

// NewUpdateImplementationAttributesParamsWithHTTPClient creates a new UpdateImplementationAttributesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateImplementationAttributesParamsWithHTTPClient(client *http.Client) *UpdateImplementationAttributesParams {
	var ()
	return &UpdateImplementationAttributesParams{
		HTTPClient: client,
	}
}

/*UpdateImplementationAttributesParams contains all the parameters to send to the API endpoint
for the update implementation attributes operation typically these are written to a http.Request
*/
type UpdateImplementationAttributesParams struct {

	/*Implementation
	  Implementation object to be updated

	*/
	Implementation *models.Implementation
	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update implementation attributes params
func (o *UpdateImplementationAttributesParams) WithTimeout(timeout time.Duration) *UpdateImplementationAttributesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update implementation attributes params
func (o *UpdateImplementationAttributesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update implementation attributes params
func (o *UpdateImplementationAttributesParams) WithContext(ctx context.Context) *UpdateImplementationAttributesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update implementation attributes params
func (o *UpdateImplementationAttributesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update implementation attributes params
func (o *UpdateImplementationAttributesParams) WithHTTPClient(client *http.Client) *UpdateImplementationAttributesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update implementation attributes params
func (o *UpdateImplementationAttributesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImplementation adds the implementation to the update implementation attributes params
func (o *UpdateImplementationAttributesParams) WithImplementation(implementation *models.Implementation) *UpdateImplementationAttributesParams {
	o.SetImplementation(implementation)
	return o
}

// SetImplementation adds the implementation to the update implementation attributes params
func (o *UpdateImplementationAttributesParams) SetImplementation(implementation *models.Implementation) {
	o.Implementation = implementation
}

// WithResourceID adds the resourceID to the update implementation attributes params
func (o *UpdateImplementationAttributesParams) WithResourceID(resourceID string) *UpdateImplementationAttributesParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the update implementation attributes params
func (o *UpdateImplementationAttributesParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateImplementationAttributesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Implementation != nil {
		if err := r.SetBodyParam(o.Implementation); err != nil {
			return err
		}
	}

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
