// Code generated by go-swagger; DO NOT EDIT.

package api_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// AddAPIVersionReader is a Reader for the AddAPIVersion structure.
type AddAPIVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddAPIVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddAPIVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAddAPIVersionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddAPIVersionOK creates a AddAPIVersionOK with default headers values
func NewAddAPIVersionOK() *AddAPIVersionOK {
	return &AddAPIVersionOK{}
}

/*AddAPIVersionOK handles this case with default header values.

Returns the created object
*/
type AddAPIVersionOK struct {
	Payload models.APIVersion
}

func (o *AddAPIVersionOK) Error() string {
	return fmt.Sprintf("[POST /apiversions][%d] addApiVersionOK  %+v", 200, o.Payload)
}

func (o *AddAPIVersionOK) GetPayload() models.APIVersion {
	return o.Payload
}

func (o *AddAPIVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddAPIVersionUnauthorized creates a AddAPIVersionUnauthorized with default headers values
func NewAddAPIVersionUnauthorized() *AddAPIVersionUnauthorized {
	return &AddAPIVersionUnauthorized{}
}

/*AddAPIVersionUnauthorized handles this case with default header values.

Unauthorized
*/
type AddAPIVersionUnauthorized struct {
}

func (o *AddAPIVersionUnauthorized) Error() string {
	return fmt.Sprintf("[POST /apiversions][%d] addApiVersionUnauthorized ", 401)
}

func (o *AddAPIVersionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
