// Code generated by go-swagger; DO NOT EDIT.

package api_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAPIVersionParams creates a new DeleteAPIVersionParams object
// with the default values initialized.
func NewDeleteAPIVersionParams() *DeleteAPIVersionParams {
	var ()
	return &DeleteAPIVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIVersionParamsWithTimeout creates a new DeleteAPIVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPIVersionParamsWithTimeout(timeout time.Duration) *DeleteAPIVersionParams {
	var ()
	return &DeleteAPIVersionParams{

		timeout: timeout,
	}
}

// NewDeleteAPIVersionParamsWithContext creates a new DeleteAPIVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPIVersionParamsWithContext(ctx context.Context) *DeleteAPIVersionParams {
	var ()
	return &DeleteAPIVersionParams{

		Context: ctx,
	}
}

// NewDeleteAPIVersionParamsWithHTTPClient creates a new DeleteAPIVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPIVersionParamsWithHTTPClient(client *http.Client) *DeleteAPIVersionParams {
	var ()
	return &DeleteAPIVersionParams{
		HTTPClient: client,
	}
}

/*DeleteAPIVersionParams contains all the parameters to send to the API endpoint
for the delete Api version operation typically these are written to a http.Request
*/
type DeleteAPIVersionParams struct {

	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete Api version params
func (o *DeleteAPIVersionParams) WithTimeout(timeout time.Duration) *DeleteAPIVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete Api version params
func (o *DeleteAPIVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete Api version params
func (o *DeleteAPIVersionParams) WithContext(ctx context.Context) *DeleteAPIVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete Api version params
func (o *DeleteAPIVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete Api version params
func (o *DeleteAPIVersionParams) WithHTTPClient(client *http.Client) *DeleteAPIVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete Api version params
func (o *DeleteAPIVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceID adds the resourceID to the delete Api version params
func (o *DeleteAPIVersionParams) WithResourceID(resourceID string) *DeleteAPIVersionParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the delete Api version params
func (o *DeleteAPIVersionParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
