// Code generated by go-swagger; DO NOT EDIT.

package api_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	ImplementationVersion "github.com/kathra-project/kathra-core-model-go/models"
)

// GetAPIVersionsReader is a Reader for the GetAPIVersions structure.
type GetAPIVersionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIVersionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIVersionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAPIVersionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIVersionsOK creates a GetAPIVersionsOK with default headers values
func NewGetAPIVersionsOK() *GetAPIVersionsOK {
	return &GetAPIVersionsOK{}
}

/*GetAPIVersionsOK handles this case with default header values.

List of accessible apiversions for the authenticated user
*/
type GetAPIVersionsOK struct {
	Payload []ImplementationVersion.ImplementationVersion
}

func (o *GetAPIVersionsOK) Error() string {
	return fmt.Sprintf("[GET /apiversions][%d] getApiVersionsOK  %+v", 200, o.Payload)
}

func (o *GetAPIVersionsOK) GetPayload() []ImplementationVersion.ImplementationVersion {
	return o.Payload
}

func (o *GetAPIVersionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIVersionsUnauthorized creates a GetAPIVersionsUnauthorized with default headers values
func NewGetAPIVersionsUnauthorized() *GetAPIVersionsUnauthorized {
	return &GetAPIVersionsUnauthorized{}
}

/*GetAPIVersionsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAPIVersionsUnauthorized struct {
}

func (o *GetAPIVersionsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apiversions][%d] getApiVersionsUnauthorized ", 401)
}

func (o *GetAPIVersionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
