// Code generated by go-swagger; DO NOT EDIT.

package api_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// UpdateAPIVersionAttributesReader is a Reader for the UpdateAPIVersionAttributes structure.
type UpdateAPIVersionAttributesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAPIVersionAttributesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateAPIVersionAttributesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateAPIVersionAttributesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateAPIVersionAttributesOK creates a UpdateAPIVersionAttributesOK with default headers values
func NewUpdateAPIVersionAttributesOK() *UpdateAPIVersionAttributesOK {
	return &UpdateAPIVersionAttributesOK{}
}

/*UpdateAPIVersionAttributesOK handles this case with default header values.

Returns the modified object
*/
type UpdateAPIVersionAttributesOK struct {
	Payload *models.APIVersion
}

func (o *UpdateAPIVersionAttributesOK) Error() string {
	return fmt.Sprintf("[PATCH /apiversions/{resourceId}][%d] updateApiVersionAttributesOK  %+v", 200, o.Payload)
}

func (o *UpdateAPIVersionAttributesOK) GetPayload() *models.APIVersion {
	return o.Payload
}

func (o *UpdateAPIVersionAttributesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIVersion)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAPIVersionAttributesUnauthorized creates a UpdateAPIVersionAttributesUnauthorized with default headers values
func NewUpdateAPIVersionAttributesUnauthorized() *UpdateAPIVersionAttributesUnauthorized {
	return &UpdateAPIVersionAttributesUnauthorized{}
}

/*UpdateAPIVersionAttributesUnauthorized handles this case with default header values.

Unauthorized
*/
type UpdateAPIVersionAttributesUnauthorized struct {
}

func (o *UpdateAPIVersionAttributesUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /apiversions/{resourceId}][%d] updateApiVersionAttributesUnauthorized ", 401)
}

func (o *UpdateAPIVersionAttributesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
