// Code generated by go-swagger; DO NOT EDIT.

package api_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	ImplementationVersion "github.com/kathra-project/kathra-core-model-go/models"
)

// NewUpdateAPIVersionParams creates a new UpdateAPIVersionParams object
// with the default values initialized.
func NewUpdateAPIVersionParams() *UpdateAPIVersionParams {
	var ()
	return &UpdateAPIVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAPIVersionParamsWithTimeout creates a new UpdateAPIVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAPIVersionParamsWithTimeout(timeout time.Duration) *UpdateAPIVersionParams {
	var ()
	return &UpdateAPIVersionParams{

		timeout: timeout,
	}
}

// NewUpdateAPIVersionParamsWithContext creates a new UpdateAPIVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAPIVersionParamsWithContext(ctx context.Context) *UpdateAPIVersionParams {
	var ()
	return &UpdateAPIVersionParams{

		Context: ctx,
	}
}

// NewUpdateAPIVersionParamsWithHTTPClient creates a new UpdateAPIVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAPIVersionParamsWithHTTPClient(client *http.Client) *UpdateAPIVersionParams {
	var ()
	return &UpdateAPIVersionParams{
		HTTPClient: client,
	}
}

/*UpdateAPIVersionParams contains all the parameters to send to the API endpoint
for the update Api version operation typically these are written to a http.Request
*/
type UpdateAPIVersionParams struct {

	/*Apiversion
	  ApiVersion object to be updated

	*/
	Apiversion ImplementationVersion.ImplementationVersion
	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update Api version params
func (o *UpdateAPIVersionParams) WithTimeout(timeout time.Duration) *UpdateAPIVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update Api version params
func (o *UpdateAPIVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update Api version params
func (o *UpdateAPIVersionParams) WithContext(ctx context.Context) *UpdateAPIVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update Api version params
func (o *UpdateAPIVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update Api version params
func (o *UpdateAPIVersionParams) WithHTTPClient(client *http.Client) *UpdateAPIVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update Api version params
func (o *UpdateAPIVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApiversion adds the apiversion to the update Api version params
func (o *UpdateAPIVersionParams) WithApiversion(apiversion ImplementationVersion.ImplementationVersion) *UpdateAPIVersionParams {
	o.SetApiversion(apiversion)
	return o
}

// SetApiversion adds the apiversion to the update Api version params
func (o *UpdateAPIVersionParams) SetApiversion(apiversion ImplementationVersion.ImplementationVersion) {
	o.Apiversion = apiversion
}

// WithResourceID adds the resourceID to the update Api version params
func (o *UpdateAPIVersionParams) WithResourceID(resourceID string) *UpdateAPIVersionParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the update Api version params
func (o *UpdateAPIVersionParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAPIVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Apiversion != nil {
		if err := r.SetBodyParam(o.Apiversion); err != nil {
			return err
		}
	}

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
