// Code generated by go-swagger; DO NOT EDIT.

package library_api_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteLibraryAPIVersionReader is a Reader for the DeleteLibraryAPIVersion structure.
type DeleteLibraryAPIVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLibraryAPIVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteLibraryAPIVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteLibraryAPIVersionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteLibraryAPIVersionOK creates a DeleteLibraryAPIVersionOK with default headers values
func NewDeleteLibraryAPIVersionOK() *DeleteLibraryAPIVersionOK {
	return &DeleteLibraryAPIVersionOK{}
}

/*DeleteLibraryAPIVersionOK handles this case with default header values.

Object is deleted
*/
type DeleteLibraryAPIVersionOK struct {
	Payload string
}

func (o *DeleteLibraryAPIVersionOK) Error() string {
	return fmt.Sprintf("[DELETE /libraryapiversions/{resourceId}][%d] deleteLibraryApiVersionOK  %+v", 200, o.Payload)
}

func (o *DeleteLibraryAPIVersionOK) GetPayload() string {
	return o.Payload
}

func (o *DeleteLibraryAPIVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLibraryAPIVersionUnauthorized creates a DeleteLibraryAPIVersionUnauthorized with default headers values
func NewDeleteLibraryAPIVersionUnauthorized() *DeleteLibraryAPIVersionUnauthorized {
	return &DeleteLibraryAPIVersionUnauthorized{}
}

/*DeleteLibraryAPIVersionUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteLibraryAPIVersionUnauthorized struct {
}

func (o *DeleteLibraryAPIVersionUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /libraryapiversions/{resourceId}][%d] deleteLibraryApiVersionUnauthorized ", 401)
}

func (o *DeleteLibraryAPIVersionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
