// Code generated by go-swagger; DO NOT EDIT.

package library_api_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// GetLibraryAPIVersionsReader is a Reader for the GetLibraryAPIVersions structure.
type GetLibraryAPIVersionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLibraryAPIVersionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLibraryAPIVersionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetLibraryAPIVersionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLibraryAPIVersionsOK creates a GetLibraryAPIVersionsOK with default headers values
func NewGetLibraryAPIVersionsOK() *GetLibraryAPIVersionsOK {
	return &GetLibraryAPIVersionsOK{}
}

/*GetLibraryAPIVersionsOK handles this case with default header values.

List of accessible libraryapiversions for the authenticated user
*/
type GetLibraryAPIVersionsOK struct {
	Payload []models.LibraryAPIVersion
}

func (o *GetLibraryAPIVersionsOK) Error() string {
	return fmt.Sprintf("[GET /libraryapiversions][%d] getLibraryApiVersionsOK  %+v", 200, o.Payload)
}

func (o *GetLibraryAPIVersionsOK) GetPayload() []models.LibraryAPIVersion {
	return o.Payload
}

func (o *GetLibraryAPIVersionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLibraryAPIVersionsUnauthorized creates a GetLibraryAPIVersionsUnauthorized with default headers values
func NewGetLibraryAPIVersionsUnauthorized() *GetLibraryAPIVersionsUnauthorized {
	return &GetLibraryAPIVersionsUnauthorized{}
}

/*GetLibraryAPIVersionsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetLibraryAPIVersionsUnauthorized struct {
}

func (o *GetLibraryAPIVersionsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /libraryapiversions][%d] getLibraryApiVersionsUnauthorized ", 401)
}

func (o *GetLibraryAPIVersionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
