// Code generated by go-swagger; DO NOT EDIT.

package library_api_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// GetLibraryAPIVersionReader is a Reader for the GetLibraryAPIVersion structure.
type GetLibraryAPIVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLibraryAPIVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLibraryAPIVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetLibraryAPIVersionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLibraryAPIVersionOK creates a GetLibraryAPIVersionOK with default headers values
func NewGetLibraryAPIVersionOK() *GetLibraryAPIVersionOK {
	return &GetLibraryAPIVersionOK{}
}

/*GetLibraryAPIVersionOK handles this case with default header values.

Returns the object
*/
type GetLibraryAPIVersionOK struct {
	Payload *models.LibraryAPIVersion
}

func (o *GetLibraryAPIVersionOK) Error() string {
	return fmt.Sprintf("[GET /libraryapiversions/{resourceId}][%d] getLibraryApiVersionOK  %+v", 200, o.Payload)
}

func (o *GetLibraryAPIVersionOK) GetPayload() *models.LibraryAPIVersion {
	return o.Payload
}

func (o *GetLibraryAPIVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LibraryAPIVersion)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLibraryAPIVersionUnauthorized creates a GetLibraryAPIVersionUnauthorized with default headers values
func NewGetLibraryAPIVersionUnauthorized() *GetLibraryAPIVersionUnauthorized {
	return &GetLibraryAPIVersionUnauthorized{}
}

/*GetLibraryAPIVersionUnauthorized handles this case with default header values.

Unauthorized
*/
type GetLibraryAPIVersionUnauthorized struct {
}

func (o *GetLibraryAPIVersionUnauthorized) Error() string {
	return fmt.Sprintf("[GET /libraryapiversions/{resourceId}][%d] getLibraryApiVersionUnauthorized ", 401)
}

func (o *GetLibraryAPIVersionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
