// Code generated by go-swagger; DO NOT EDIT.

package library_api_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	LibraryApiVersion "github.com/kathra-project/kathra-core-model-go/models"
)

// UpdateLibraryAPIVersionReader is a Reader for the UpdateLibraryAPIVersion structure.
type UpdateLibraryAPIVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateLibraryAPIVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateLibraryAPIVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateLibraryAPIVersionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateLibraryAPIVersionOK creates a UpdateLibraryAPIVersionOK with default headers values
func NewUpdateLibraryAPIVersionOK() *UpdateLibraryAPIVersionOK {
	return &UpdateLibraryAPIVersionOK{}
}

/*UpdateLibraryAPIVersionOK handles this case with default header values.

Returns the modified object
*/
type UpdateLibraryAPIVersionOK struct {
	Payload LibraryApiVersion.LibraryApiVersion
}

func (o *UpdateLibraryAPIVersionOK) Error() string {
	return fmt.Sprintf("[PUT /libraryapiversions/{resourceId}][%d] updateLibraryApiVersionOK  %+v", 200, o.Payload)
}

func (o *UpdateLibraryAPIVersionOK) GetPayload() LibraryApiVersion.LibraryApiVersion {
	return o.Payload
}

func (o *UpdateLibraryAPIVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateLibraryAPIVersionUnauthorized creates a UpdateLibraryAPIVersionUnauthorized with default headers values
func NewUpdateLibraryAPIVersionUnauthorized() *UpdateLibraryAPIVersionUnauthorized {
	return &UpdateLibraryAPIVersionUnauthorized{}
}

/*UpdateLibraryAPIVersionUnauthorized handles this case with default header values.

Unauthorized
*/
type UpdateLibraryAPIVersionUnauthorized struct {
}

func (o *UpdateLibraryAPIVersionUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /libraryapiversions/{resourceId}][%d] updateLibraryApiVersionUnauthorized ", 401)
}

func (o *UpdateLibraryAPIVersionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
