// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// AddComponentReader is a Reader for the AddComponent structure.
type AddComponentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddComponentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddComponentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAddComponentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddComponentOK creates a AddComponentOK with default headers values
func NewAddComponentOK() *AddComponentOK {
	return &AddComponentOK{}
}

/*AddComponentOK handles this case with default header values.

Returns the created object
*/
type AddComponentOK struct {
	Payload models.Component
}

func (o *AddComponentOK) Error() string {
	return fmt.Sprintf("[POST /components][%d] addComponentOK  %+v", 200, o.Payload)
}

func (o *AddComponentOK) GetPayload() models.Component {
	return o.Payload
}

func (o *AddComponentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddComponentUnauthorized creates a AddComponentUnauthorized with default headers values
func NewAddComponentUnauthorized() *AddComponentUnauthorized {
	return &AddComponentUnauthorized{}
}

/*AddComponentUnauthorized handles this case with default header values.

Unauthorized
*/
type AddComponentUnauthorized struct {
}

func (o *AddComponentUnauthorized) Error() string {
	return fmt.Sprintf("[POST /components][%d] addComponentUnauthorized ", 401)
}

func (o *AddComponentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
