// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	Component "github.com/kathra-project/kathra-core-model-go/models"
)

// GetComponentsReader is a Reader for the GetComponents structure.
type GetComponentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetComponentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetComponentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetComponentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetComponentsOK creates a GetComponentsOK with default headers values
func NewGetComponentsOK() *GetComponentsOK {
	return &GetComponentsOK{}
}

/*GetComponentsOK handles this case with default header values.

List of accessible components for the authenticated user
*/
type GetComponentsOK struct {
	Payload []Component.Component
}

func (o *GetComponentsOK) Error() string {
	return fmt.Sprintf("[GET /components][%d] getComponentsOK  %+v", 200, o.Payload)
}

func (o *GetComponentsOK) GetPayload() []Component.Component {
	return o.Payload
}

func (o *GetComponentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetComponentsUnauthorized creates a GetComponentsUnauthorized with default headers values
func NewGetComponentsUnauthorized() *GetComponentsUnauthorized {
	return &GetComponentsUnauthorized{}
}

/*GetComponentsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetComponentsUnauthorized struct {
}

func (o *GetComponentsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /components][%d] getComponentsUnauthorized ", 401)
}

func (o *GetComponentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
