// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	Implementation "github.com/kathra-project/kathra-core-model-go/models"
)

// GetImplementationsComponentReader is a Reader for the GetImplementationsComponent structure.
type GetImplementationsComponentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImplementationsComponentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetImplementationsComponentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetImplementationsComponentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetImplementationsComponentOK creates a GetImplementationsComponentOK with default headers values
func NewGetImplementationsComponentOK() *GetImplementationsComponentOK {
	return &GetImplementationsComponentOK{}
}

/*GetImplementationsComponentOK handles this case with default header values.

List of accessible implementations for specific component and the authenticated user
*/
type GetImplementationsComponentOK struct {
	Payload []Implementation.Implementation
}

func (o *GetImplementationsComponentOK) Error() string {
	return fmt.Sprintf("[GET /components/{resourceId}/implementations][%d] getImplementationsComponentOK  %+v", 200, o.Payload)
}

func (o *GetImplementationsComponentOK) GetPayload() []Implementation.Implementation {
	return o.Payload
}

func (o *GetImplementationsComponentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImplementationsComponentUnauthorized creates a GetImplementationsComponentUnauthorized with default headers values
func NewGetImplementationsComponentUnauthorized() *GetImplementationsComponentUnauthorized {
	return &GetImplementationsComponentUnauthorized{}
}

/*GetImplementationsComponentUnauthorized handles this case with default header values.

Unauthorized
*/
type GetImplementationsComponentUnauthorized struct {
}

func (o *GetImplementationsComponentUnauthorized) Error() string {
	return fmt.Sprintf("[GET /components/{resourceId}/implementations][%d] getImplementationsComponentUnauthorized ", 401)
}

func (o *GetImplementationsComponentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
