// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetImplementationsComponentParams creates a new GetImplementationsComponentParams object
// with the default values initialized.
func NewGetImplementationsComponentParams() *GetImplementationsComponentParams {
	var ()
	return &GetImplementationsComponentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetImplementationsComponentParamsWithTimeout creates a new GetImplementationsComponentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetImplementationsComponentParamsWithTimeout(timeout time.Duration) *GetImplementationsComponentParams {
	var ()
	return &GetImplementationsComponentParams{

		timeout: timeout,
	}
}

// NewGetImplementationsComponentParamsWithContext creates a new GetImplementationsComponentParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetImplementationsComponentParamsWithContext(ctx context.Context) *GetImplementationsComponentParams {
	var ()
	return &GetImplementationsComponentParams{

		Context: ctx,
	}
}

// NewGetImplementationsComponentParamsWithHTTPClient creates a new GetImplementationsComponentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetImplementationsComponentParamsWithHTTPClient(client *http.Client) *GetImplementationsComponentParams {
	var ()
	return &GetImplementationsComponentParams{
		HTTPClient: client,
	}
}

/*GetImplementationsComponentParams contains all the parameters to send to the API endpoint
for the get implementations component operation typically these are written to a http.Request
*/
type GetImplementationsComponentParams struct {

	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get implementations component params
func (o *GetImplementationsComponentParams) WithTimeout(timeout time.Duration) *GetImplementationsComponentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get implementations component params
func (o *GetImplementationsComponentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get implementations component params
func (o *GetImplementationsComponentParams) WithContext(ctx context.Context) *GetImplementationsComponentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get implementations component params
func (o *GetImplementationsComponentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get implementations component params
func (o *GetImplementationsComponentParams) WithHTTPClient(client *http.Client) *GetImplementationsComponentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get implementations component params
func (o *GetImplementationsComponentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceID adds the resourceID to the get implementations component params
func (o *GetImplementationsComponentParams) WithResourceID(resourceID string) *GetImplementationsComponentParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the get implementations component params
func (o *GetImplementationsComponentParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetImplementationsComponentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
