// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetComponentParams creates a new GetComponentParams object
// with the default values initialized.
func NewGetComponentParams() *GetComponentParams {
	var ()
	return &GetComponentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetComponentParamsWithTimeout creates a new GetComponentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetComponentParamsWithTimeout(timeout time.Duration) *GetComponentParams {
	var ()
	return &GetComponentParams{

		timeout: timeout,
	}
}

// NewGetComponentParamsWithContext creates a new GetComponentParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetComponentParamsWithContext(ctx context.Context) *GetComponentParams {
	var ()
	return &GetComponentParams{

		Context: ctx,
	}
}

// NewGetComponentParamsWithHTTPClient creates a new GetComponentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetComponentParamsWithHTTPClient(client *http.Client) *GetComponentParams {
	var ()
	return &GetComponentParams{
		HTTPClient: client,
	}
}

/*GetComponentParams contains all the parameters to send to the API endpoint
for the get component operation typically these are written to a http.Request
*/
type GetComponentParams struct {

	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get component params
func (o *GetComponentParams) WithTimeout(timeout time.Duration) *GetComponentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get component params
func (o *GetComponentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get component params
func (o *GetComponentParams) WithContext(ctx context.Context) *GetComponentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get component params
func (o *GetComponentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get component params
func (o *GetComponentParams) WithHTTPClient(client *http.Client) *GetComponentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get component params
func (o *GetComponentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceID adds the resourceID to the get component params
func (o *GetComponentParams) WithResourceID(resourceID string) *GetComponentParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the get component params
func (o *GetComponentParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetComponentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
