// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	Component "github.com/kathra-project/kathra-core-model-go/models"
)

// UpdateComponentAttributesReader is a Reader for the UpdateComponentAttributes structure.
type UpdateComponentAttributesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateComponentAttributesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateComponentAttributesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateComponentAttributesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateComponentAttributesOK creates a UpdateComponentAttributesOK with default headers values
func NewUpdateComponentAttributesOK() *UpdateComponentAttributesOK {
	return &UpdateComponentAttributesOK{}
}

/*UpdateComponentAttributesOK handles this case with default header values.

Returns the modified object
*/
type UpdateComponentAttributesOK struct {
	Payload Component.Component
}

func (o *UpdateComponentAttributesOK) Error() string {
	return fmt.Sprintf("[PATCH /components/{resourceId}][%d] updateComponentAttributesOK  %+v", 200, o.Payload)
}

func (o *UpdateComponentAttributesOK) GetPayload() Component.Component {
	return o.Payload
}

func (o *UpdateComponentAttributesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateComponentAttributesUnauthorized creates a UpdateComponentAttributesUnauthorized with default headers values
func NewUpdateComponentAttributesUnauthorized() *UpdateComponentAttributesUnauthorized {
	return &UpdateComponentAttributesUnauthorized{}
}

/*UpdateComponentAttributesUnauthorized handles this case with default header values.

Unauthorized
*/
type UpdateComponentAttributesUnauthorized struct {
}

func (o *UpdateComponentAttributesUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /components/{resourceId}][%d] updateComponentAttributesUnauthorized ", 401)
}

func (o *UpdateComponentAttributesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
