// Code generated by go-swagger; DO NOT EDIT.

package libraries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteLibraryReader is a Reader for the DeleteLibrary structure.
type DeleteLibraryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLibraryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteLibraryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteLibraryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteLibraryOK creates a DeleteLibraryOK with default headers values
func NewDeleteLibraryOK() *DeleteLibraryOK {
	return &DeleteLibraryOK{}
}

/*DeleteLibraryOK handles this case with default header values.

Object is deleted
*/
type DeleteLibraryOK struct {
	Payload string
}

func (o *DeleteLibraryOK) Error() string {
	return fmt.Sprintf("[DELETE /libraries/{resourceId}][%d] deleteLibraryOK  %+v", 200, o.Payload)
}

func (o *DeleteLibraryOK) GetPayload() string {
	return o.Payload
}

func (o *DeleteLibraryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLibraryUnauthorized creates a DeleteLibraryUnauthorized with default headers values
func NewDeleteLibraryUnauthorized() *DeleteLibraryUnauthorized {
	return &DeleteLibraryUnauthorized{}
}

/*DeleteLibraryUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteLibraryUnauthorized struct {
}

func (o *DeleteLibraryUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /libraries/{resourceId}][%d] deleteLibraryUnauthorized ", 401)
}

func (o *DeleteLibraryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
