// Code generated by go-swagger; DO NOT EDIT.

package libraries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLibraryParams creates a new GetLibraryParams object
// with the default values initialized.
func NewGetLibraryParams() *GetLibraryParams {
	var ()
	return &GetLibraryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLibraryParamsWithTimeout creates a new GetLibraryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLibraryParamsWithTimeout(timeout time.Duration) *GetLibraryParams {
	var ()
	return &GetLibraryParams{

		timeout: timeout,
	}
}

// NewGetLibraryParamsWithContext creates a new GetLibraryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLibraryParamsWithContext(ctx context.Context) *GetLibraryParams {
	var ()
	return &GetLibraryParams{

		Context: ctx,
	}
}

// NewGetLibraryParamsWithHTTPClient creates a new GetLibraryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLibraryParamsWithHTTPClient(client *http.Client) *GetLibraryParams {
	var ()
	return &GetLibraryParams{
		HTTPClient: client,
	}
}

/*GetLibraryParams contains all the parameters to send to the API endpoint
for the get library operation typically these are written to a http.Request
*/
type GetLibraryParams struct {

	/*ResourceID
	  resource's id

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get library params
func (o *GetLibraryParams) WithTimeout(timeout time.Duration) *GetLibraryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get library params
func (o *GetLibraryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get library params
func (o *GetLibraryParams) WithContext(ctx context.Context) *GetLibraryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get library params
func (o *GetLibraryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get library params
func (o *GetLibraryParams) WithHTTPClient(client *http.Client) *GetLibraryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get library params
func (o *GetLibraryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceID adds the resourceID to the get library params
func (o *GetLibraryParams) WithResourceID(resourceID string) *GetLibraryParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the get library params
func (o *GetLibraryParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetLibraryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
