// Code generated by go-swagger; DO NOT EDIT.

package libraries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// GetLibrariesReader is a Reader for the GetLibraries structure.
type GetLibrariesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLibrariesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLibrariesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetLibrariesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLibrariesOK creates a GetLibrariesOK with default headers values
func NewGetLibrariesOK() *GetLibrariesOK {
	return &GetLibrariesOK{}
}

/*GetLibrariesOK handles this case with default header values.

List of accessible libraries for the authenticated user
*/
type GetLibrariesOK struct {
	Payload []*models.Library
}

func (o *GetLibrariesOK) Error() string {
	return fmt.Sprintf("[GET /libraries][%d] getLibrariesOK  %+v", 200, o.Payload)
}

func (o *GetLibrariesOK) GetPayload() []*models.Library {
	return o.Payload
}

func (o *GetLibrariesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLibrariesUnauthorized creates a GetLibrariesUnauthorized with default headers values
func NewGetLibrariesUnauthorized() *GetLibrariesUnauthorized {
	return &GetLibrariesUnauthorized{}
}

/*GetLibrariesUnauthorized handles this case with default header values.

Unauthorized
*/
type GetLibrariesUnauthorized struct {
}

func (o *GetLibrariesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /libraries][%d] getLibrariesUnauthorized ", 401)
}

func (o *GetLibrariesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
