// Code generated by go-swagger; DO NOT EDIT.

package libraries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kathra-project/kathra-resourcemanager-client-go/models"
)

// UpdateLibraryAttributesReader is a Reader for the UpdateLibraryAttributes structure.
type UpdateLibraryAttributesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateLibraryAttributesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateLibraryAttributesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateLibraryAttributesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateLibraryAttributesOK creates a UpdateLibraryAttributesOK with default headers values
func NewUpdateLibraryAttributesOK() *UpdateLibraryAttributesOK {
	return &UpdateLibraryAttributesOK{}
}

/*UpdateLibraryAttributesOK handles this case with default header values.

Returns the modified object
*/
type UpdateLibraryAttributesOK struct {
	Payload models.Library
}

func (o *UpdateLibraryAttributesOK) Error() string {
	return fmt.Sprintf("[PATCH /libraries/{resourceId}][%d] updateLibraryAttributesOK  %+v", 200, o.Payload)
}

func (o *UpdateLibraryAttributesOK) GetPayload() models.Library {
	return o.Payload
}

func (o *UpdateLibraryAttributesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateLibraryAttributesUnauthorized creates a UpdateLibraryAttributesUnauthorized with default headers values
func NewUpdateLibraryAttributesUnauthorized() *UpdateLibraryAttributesUnauthorized {
	return &UpdateLibraryAttributesUnauthorized{}
}

/*UpdateLibraryAttributesUnauthorized handles this case with default header values.

Unauthorized
*/
type UpdateLibraryAttributesUnauthorized struct {
}

func (o *UpdateLibraryAttributesUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /libraries/{resourceId}][%d] updateLibraryAttributesUnauthorized ", 401)
}

func (o *UpdateLibraryAttributesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
