// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// BinaryRepository binary repository
// swagger:model BinaryRepository
type BinaryRepository struct {
	Resource

	// group
	Group *Group `json:"group,omitempty"`

	// provider
	Provider string `json:"provider,omitempty"`

	// provider Id
	ProviderID string `json:"providerId,omitempty"`

	// snapshot
	Snapshot bool `json:"snapshot,omitempty"`

	// type
	// Enum: [JAVA PYTHON DOCKER_IMAGE HELM]
	Type interface{} `json:"type,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *BinaryRepository) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Resource
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Resource = aO0

	// AO1
	var dataAO1 struct {
		Group *Group `json:"group,omitempty"`

		Provider string `json:"provider,omitempty"`

		ProviderID string `json:"providerId,omitempty"`

		Snapshot bool `json:"snapshot,omitempty"`

		Type interface{} `json:"type,omitempty"`

		URL string `json:"url,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Group = dataAO1.Group

	m.Provider = dataAO1.Provider

	m.ProviderID = dataAO1.ProviderID

	m.Snapshot = dataAO1.Snapshot

	m.Type = dataAO1.Type

	m.URL = dataAO1.URL

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m BinaryRepository) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.Resource)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		Group *Group `json:"group,omitempty"`

		Provider string `json:"provider,omitempty"`

		ProviderID string `json:"providerId,omitempty"`

		Snapshot bool `json:"snapshot,omitempty"`

		Type interface{} `json:"type,omitempty"`

		URL string `json:"url,omitempty"`
	}

	dataAO1.Group = m.Group

	dataAO1.Provider = m.Provider

	dataAO1.ProviderID = m.ProviderID

	dataAO1.Snapshot = m.Snapshot

	dataAO1.Type = m.Type

	dataAO1.URL = m.URL

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this binary repository
func (m *BinaryRepository) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Resource
	if err := m.Resource.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGroup(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BinaryRepository) validateGroup(formats strfmt.Registry) error {

	if swag.IsZero(m.Group) { // not required
		return nil
	}

	if m.Group != nil {
		if err := m.Group.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("group")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BinaryRepository) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BinaryRepository) UnmarshalBinary(b []byte) error {
	var res BinaryRepository
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
