// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// BuildArgument build argument
// swagger:model BuildArgument
type BuildArgument struct {

	// Build argument key
	Key string `json:"key,omitempty"`

	// Build argument value
	Value string `json:"value,omitempty"`
}

// Validate validates this build argument
func (m *BuildArgument) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BuildArgument) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuildArgument) UnmarshalBinary(b []byte) error {
	var res BuildArgument
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
