// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// PACKAGETYPE p a c k a g e t y p e
// swagger:model PACKAGE_TYPE
type PACKAGETYPE string

const (

	// PACKAGETYPEHELM captures enum value "HELM"
	PACKAGETYPEHELM PACKAGETYPE = "HELM"
)

// for schema
var pACKAGETYPEEnum []interface{}

func init() {
	var res []PACKAGETYPE
	if err := json.Unmarshal([]byte(`["HELM"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		pACKAGETYPEEnum = append(pACKAGETYPEEnum, v)
	}
}

func (m PACKAGETYPE) validatePACKAGETYPEEnum(path, location string, value PACKAGETYPE) error {
	if err := validate.Enum(path, location, value, pACKAGETYPEEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this p a c k a g e t y p e
func (m PACKAGETYPE) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePACKAGETYPEEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
